name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      # 1) Repo'yu çek
      - name: Kodları Çek
        uses: actions/checkout@v4

      # 2) AutoHotkey + Ahk2Exe indir
      - name: Bağımlılıkları İndir
        shell: pwsh
        run: |
          Invoke-WebRequest `
            -Uri "https://github.com/AutoHotkey/AutoHotkey/releases/download/v2.0.20/AutoHotkey_2.0.20.zip" `
            -OutFile "ahk.zip"

          Invoke-WebRequest `
            -Uri "https://github.com/AutoHotkey/Ahk2Exe/releases/download/Ahk2Exe1.1.37.02a0a/Ahk2Exe1.1.37.02a0.zip" `
            -OutFile "compiler.zip"

          Expand-Archive ahk.zip -DestinationPath ahk
          Expand-Archive compiler.zip -DestinationPath ahk

      # 3) Derleme (src klasöründe çalıştırılır)
      - name: Derleme (x64 ve x32)
        shell: pwsh
        run: |
          $compiler = "..\ahk\Ahk2Exe.exe"
          $ahk64    = "..\ahk\AutoHotkey64.exe"
          $ahk32    = "..\ahk\AutoHotkey32.exe"

          if (!(Test-Path "ahk\Ahk2Exe.exe")) {
              Write-Error "Ahk2Exe.exe bulunamadı"
              exit 1
          }

          if (!(Test-Path "ahk\AutoHotkey64.exe") -or !(Test-Path "ahk\AutoHotkey32.exe")) {
              Write-Error "AutoHotkey exe bulunamadı"
              exit 1
          }

          Push-Location src

          # x64
          & $compiler `
            /in "pixel color.ahk" `
            /base $ahk64 `
            /out "..\AS-Pixel-Color-x64.exe"

          # x32
          & $compiler `
            /in "pixel color.ahk" `
            /base $ahk32 `
            /out "..\AS-Pixel-Color-x32.exe"

          Pop-Location

      # 4) Exe gerçekten oluştu mu kontrol
      - name: Çıktı Kontrol
        shell: pwsh
        run: |
          if (!(Test-Path "AS-Pixel-Color-x64.exe") -or !(Test-Path "AS-Pixel-Color-x32.exe")) {
              Write-Error "Exe dosyaları oluşmadı"
              exit 1
          }

      # 5) Release oluştur
      - name: Release Oluştur
        uses: softprops/action-gh-release@v2
        with:
          files: |
            AS-Icon-Viewer-x64.exe
            AS-Icon-Viewer-x32.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
